# Generated by Django 3.2.4 on 2021-06-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hourlydata_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlydata',
            options={'verbose_name': 'Hourly', 'verbose_name_plural': 'Hourly'},
        ),
        migrations.RemoveField(
            model_name='hourlydata',
            name='json_data',
        ),
    ]
